#!/bin/bash

if [ -f $HOME/.tendril ]; then
  echo "Loading Tendril Config"
  source $HOME/.tendril
fi

if [ -f spec/spec_helper.rb ] && grep -q minitest spec/spec_helper.rb; then
  RUBY_TEST_COMMAND="rake TEST=$1"
else
  RUBY_TEST_COMMAND=rspec
fi

echo "Using $RUBY_TEST_COMMAND"

if [ -S .zeus.sock ]; then
  zeus $RUBY_TEST_COMMAND "$@"
else
  bundle exec $RUBY_TEST_COMMAND 
  echo "COMMAND $RUBY_TEST_COMMAND $@"
fi
